max_life_time = 86400

[filter]
[filter.vad]
start_win = 10
stop_win = 10

[stt]
select = "ali"

[stt.ali]
url = "wss://nls-gateway.cn-shanghai.aliyuncs.com/ws/v1"
akid = ""
akkey = ""
appkey = ""

[stt.ms]
speech_key = "59e03d7b53714f4d8595d7590f0854a2"
speech_region = "eastasia"
language_check_mode = 0
auto_audio_check_language = ["zh-CN", "en-US", "ja-JP"]
specify_language = "zh-CN"
set_log = false

[tts]
select = "ali"

[tts.ali]
url = "https://nls-gateway-cn-shanghai.aliyuncs.com/stream/v1/tts"
akid = ""
akkey = ""
appkey = ""

[tts.ms]
speech_key = ""
speech_region = "eastasia"
set_log = false
language_check_mode = 0
specify_language = "zh-CN"

[rtc]
app_id = ""
channel_name = "local-1"
user_id = "0"
region = "glob"

[log]
file = "./demo.log"
level = "debug"

[llm]
model_select = "qwen"
with_history = true
clause_mode = "punctuation"

[llm.prompt]
output_language = ["zh-CN"]

[llm.qwen]
model = "qwen-plus"
url = "https://dashscope.aliyuncs.com/api/v1/services/aigc/text-generation/generation"
apikey = ""
dialog_nums = 10

[llm.chat_gpt4o]
key = ""
model = "gpt-4o-west-us"
end_point = "https://gpt-4o-west-us.openai.azure.com/"
dialog_nums = 10