// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: aigc.proto

package aigcmsg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AigcMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Magicnum  int32  `protobuf:"varint,1,opt,name=magicnum,proto3" json:"magicnum,omitempty"` // 注意：proto3 中 [default] 选项是无效的，它仅在 proto2 中有效;需要人工设定
	Type      int32  `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`         // 100-stt， 120–llm； 130--tts；140-会话状态
	Version   int32  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`   //初始化默认都是1
	Userid    int32  `protobuf:"varint,4,opt,name=userid,proto3" json:"userid,omitempty"`
	Roundid   int32  `protobuf:"varint,5,opt,name=roundid,proto3" json:"roundid,omitempty"`
	Flag      int32  `protobuf:"varint,6,opt,name=flag,proto3" json:"flag,omitempty"`
	Content   string `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp int64  `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *AigcMessage) Reset() {
	*x = AigcMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aigc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AigcMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AigcMessage) ProtoMessage() {}

func (x *AigcMessage) ProtoReflect() protoreflect.Message {
	mi := &file_aigc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AigcMessage.ProtoReflect.Descriptor instead.
func (*AigcMessage) Descriptor() ([]byte, []int) {
	return file_aigc_proto_rawDescGZIP(), []int{0}
}

func (x *AigcMessage) GetMagicnum() int32 {
	if x != nil {
		return x.Magicnum
	}
	return 0
}

func (x *AigcMessage) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *AigcMessage) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *AigcMessage) GetUserid() int32 {
	if x != nil {
		return x.Userid
	}
	return 0
}

func (x *AigcMessage) GetRoundid() int32 {
	if x != nil {
		return x.Roundid
	}
	return 0
}

func (x *AigcMessage) GetFlag() int32 {
	if x != nil {
		return x.Flag
	}
	return 0
}

func (x *AigcMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *AigcMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_aigc_proto protoreflect.FileDescriptor

var file_aigc_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x61, 0x69, 0x67, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x61, 0x69,
	0x67, 0x63, 0x22, 0xd5, 0x01, 0x0a, 0x0b, 0x41, 0x69, 0x67, 0x63, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x61, 0x67, 0x69, 0x63, 0x6e, 0x75, 0x6d, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6d, 0x61, 0x67, 0x69, 0x63, 0x6e, 0x75, 0x6d, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x69, 0x64, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x66, 0x6c,
	0x61, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x3b,
	0x61, 0x69, 0x67, 0x63, 0x6d, 0x73, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_aigc_proto_rawDescOnce sync.Once
	file_aigc_proto_rawDescData = file_aigc_proto_rawDesc
)

func file_aigc_proto_rawDescGZIP() []byte {
	file_aigc_proto_rawDescOnce.Do(func() {
		file_aigc_proto_rawDescData = protoimpl.X.CompressGZIP(file_aigc_proto_rawDescData)
	})
	return file_aigc_proto_rawDescData
}

var file_aigc_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_aigc_proto_goTypes = []any{
	(*AigcMessage)(nil), // 0: aigc.AigcMessage
}
var file_aigc_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_aigc_proto_init() }
func file_aigc_proto_init() {
	if File_aigc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_aigc_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*AigcMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_aigc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_aigc_proto_goTypes,
		DependencyIndexes: file_aigc_proto_depIdxs,
		MessageInfos:      file_aigc_proto_msgTypes,
	}.Build()
	File_aigc_proto = out.File
	file_aigc_proto_rawDesc = nil
	file_aigc_proto_goTypes = nil
	file_aigc_proto_depIdxs = nil
}
